apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-html
  namespace: lesson231
data:
  index.html: |
    <html>
    <body>
    WOW. It's rly w0rks!!!
    </body>
    </html>
---
apiVersion: v1
kind: Secret
metadata:
  name: test-kuber-tls
  namespace: lesson231
stringData:
  tls.crt: |
    LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUZhekNDQTFPZ0F3SUJBZ0lVRzU2WE92bG9L
    Rkd4YmQxbVAwbCtUNFZQYUR3d0RRWUpLb1pJaHZjTkFRRUwKQlFBd1JURUxNQWtHQTFVRUJoTUNV
    bFV4RXpBUkJnTlZCQWdNQ2xOdmJXVXRVM1JoZEdVeElUQWZCZ05WQkFvTQpHRWx1ZEdWeWJtVjBJ
    RmRwWkdkcGRITWdVSFI1SUV4MFpEQWVGdzB5TlRBek1Ua3lNVEl6TkRSYUZ3MHpOVEF6Ck1UY3lN
    VEl6TkRSYU1FVXhDekFKQmdOVkJBWVRBbEpWTVJNd0VRWURWUVFJREFwVGIyMWxMVk4wWVhSbE1T
    RXcKSHdZRFZRUUtEQmhKYm5SbGNtNWxkQ0JYYVdSbmFYUnpJRkIwZVNCTWRHUXdnZ0lpTUEwR0NT
    cUdTSWIzRFFFQgpBUVVBQTRJQ0R3QXdnZ0lLQW9JQ0FRQ0xEN1VPR3YyT0NRbnBHZ09Fejdhaksw
    VjhZZFhHSzl4aStIZ1JjRDZUCnBOeG9BN1JyU1pTck1TdDBkcng2bHpzTm1RNTlCVlQrMVZ6U1o3
    NzJ1bmJ6MUFwZmMvN3FzbUp0NEFseWJIZlEKM0YwMzFqdThXRjYrZjBJLzIzZytBOXJUWU5xS2JY
    WkNWMGErVkJSZjlyR1NncVNLc0lCa0VadzF2Y3pNd3ZxbgoyV0JwUzlkM2xRcDRUNEJtNm9VUVUx
    LzE5MllCcXpnZkFLQTJTMlZCUkhpSTh3S3l6OUhFT3BJbERCdS9MT0IyClpObWQ0bDhZaXNiTlUr
    QTNyNFZQd2IybGtPbUNXL0RoN2FRVFVKNGVLUVI1eWxkbmhRdXVRS1ZlU21PREdtaFoKTk1YN0gz
    dkw4ZjgyQUM1SU14bWpocTMwZGgzKzlZZ0FJby9uRmRBMUZxRVpUVkcwbnNqeGsrMDJLdmNKbTdy
    Qgo4aXYwZFpEUFBWdUVQbmZZdmVMZWo0MWdHVFpYbFNWY0FGRUVJOFVBdnM5MThOMUNXQ2dnMmJa
    QTdUOFpVWWdwClVhckNWbDNBUnAzR3BTemRYVW8vbmxsODhXWkpScElqbG1DZWF4WFhkU1I4L21D
    R3MyYWN0RUVNc1VkNkVUMGEKZFZmaGJkcW1wZkRhcFcrSlF5d2Q2L2IvTVlQN1hWRkZpd0NMaGNH
    djVlRk9WeWpCcGllRGNiZzlIdEVyVW5FdApONWkxRzUyMEU1WTBhUWM1aDQwY0NaSFpMV3AyYkdL
    dEFEVFRIQmRhVU9UNHpXRFFYQ0RmckI5T29YYjlGcjhiCk50RjdwYndTMVV6bWk1NXh6eTVLZnlv
    QUN2ZWZSWUx6WWJjU09EdlFldUs3VWF5ckMvR0s1Ymhhd3dpajVUbTYKYXdJREFRQUJvMU13VVRB
    ZEJnTlZIUTRFRmdRVXNzSlBaOGFCWC94cDlqeG1OM25OREhIZEs5WXdId1lEVlIwagpCQmd3Rm9B
    VXNzSlBaOGFCWC94cDlqeG1OM25OREhIZEs5WXdEd1lEVlIwVEFRSC9CQVV3QXdFQi96QU5CZ2tx
    CmhraUc5dzBCQVFzRkFBT0NBZ0VBRU5nSEtuTEZHcmxONnVUY2pFbWJkLzQ3VnlYbjhXY2lpUzhQ
    VDlGUTN5cTQKS3JtaDRLaE5TNktJTzYycGpWK3FZbS9DZHA4bitudThORjZCMUZ5bnBJY211aUNM
    b1IwVkpxbzM1azJ0a3ZabQpvQVFNT1Q2Nk1zNTRwVStxMDBrcXZmc3pRNk1Ha053WDRLSm1hRjlX
    NmxVdmhwUkdNUjVOQUt6UEUrVUhTL1BLCmsyNUNFNVhFa2kvNXVJVDZyb1ZjZ1JtSkNPQS80OUNT
    bG52a1JqckVnZloxWnN5eHl4cHlSQWUxWGJpQlVYUzYKR1pkS3A2WlIvWHpJZ05UdmFxb0VJSXZF
    enZhMTR3YlVCWHhlREdlR2txWmVZSjB5NXJUTDA4VHN1dENDNFNUdAp4aWF6WkpMMUNYZFJzcExI
    NnRpa2VGNlZEVFBsdHloVmdMYmo0TDZSbk9ySCtSOVBzR29GV0E0OVhULzBuQXdXCjNrOHRTTVNr
    emg1enhaWXFjYTJaZEFZRUFSU0djMGVieHlWVkI4eG1FRU41RUZuSExOTDN0bENlajVHQy9ZK0EK
    OFVEVnRPdXZEeFJaNzdvMW5PdDBsTDB1T2NhcXQ0UVNEWGZDSnpMS3c0Y3ZpRWRWMnVYTCtJUnNR
    SjN0TEtMZApXMkZmZGFINldsQk84Z0k5dzc5amlhVUczQkpjQ0h1M1FiSXFVMEVPUHdoYUJIcGdx
    bjM0SzdEM1pGYjJOUnpHCjNZNW5xbVE3MFExaTF2Y1poT1I0Qk45WVJlRDFFTlhnQjhjUlBLUFVV
    eUFza0sxdVpsTE9CUDRwV3Q1MWY5U0IKSzNEVmJUK3hLSXZCa3hZeHppZTNZVUQvVDlzVXpIUGVV
    WS8zTnQ0Z0dVRUI5ZGVLQjdweXo3L2xVbVVqdG9RPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0t
    Cg==
  tls.key: |
    LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUpRZ0lCQURBTkJna3Foa2lHOXcwQkFRRUZB
    QVNDQ1N3d2dna29BZ0VBQW9JQ0FRQ0xEN1VPR3YyT0NRbnAKR2dPRXo3YWpLMFY4WWRYR0s5eGkr
    SGdSY0Q2VHBOeG9BN1JyU1pTck1TdDBkcng2bHpzTm1RNTlCVlQrMVZ6UwpaNzcydW5iejFBcGZj
    Lzdxc21KdDRBbHliSGZRM0YwMzFqdThXRjYrZjBJLzIzZytBOXJUWU5xS2JYWkNWMGErClZCUmY5
    ckdTZ3FTS3NJQmtFWncxdmN6TXd2cW4yV0JwUzlkM2xRcDRUNEJtNm9VUVUxLzE5MllCcXpnZkFL
    QTIKUzJWQlJIaUk4d0t5ejlIRU9wSWxEQnUvTE9CMlpObWQ0bDhZaXNiTlUrQTNyNFZQd2IybGtP
    bUNXL0RoN2FRVApVSjRlS1FSNXlsZG5oUXV1UUtWZVNtT0RHbWhaTk1YN0gzdkw4ZjgyQUM1SU14
    bWpocTMwZGgzKzlZZ0FJby9uCkZkQTFGcUVaVFZHMG5zanhrKzAyS3ZjSm03ckI4aXYwZFpEUFBW
    dUVQbmZZdmVMZWo0MWdHVFpYbFNWY0FGRUUKSThVQXZzOTE4TjFDV0NnZzJiWkE3VDhaVVlncFVh
    ckNWbDNBUnAzR3BTemRYVW8vbmxsODhXWkpScElqbG1DZQpheFhYZFNSOC9tQ0dzMmFjdEVFTXNV
    ZDZFVDBhZFZmaGJkcW1wZkRhcFcrSlF5d2Q2L2IvTVlQN1hWRkZpd0NMCmhjR3Y1ZUZPVnlqQnBp
    ZURjYmc5SHRFclVuRXRONWkxRzUyMEU1WTBhUWM1aDQwY0NaSFpMV3AyYkdLdEFEVFQKSEJkYVVP
    VDR6V0RRWENEZnJCOU9vWGI5RnI4Yk50RjdwYndTMVV6bWk1NXh6eTVLZnlvQUN2ZWZSWUx6WWJj
    UwpPRHZRZXVLN1VheXJDL0dLNWJoYXd3aWo1VG02YXdJREFRQUJBb0lDQUFDK3lMR0JiNzhaQW1v
    SUs0djlxbEU5ClVuWG1FM0EyeDB0NDd2a2c4NlRtc2c4L3dXT3BYRW5VVzcyWDdxUTFqR0o0WWRu
    VUhnclRsRmZoTnEyUEtFTmYKME1KcWE3bmU3NGhUNE81cVl4Q3BtRlhhS05oMlZhckRCV05RcXBF
    VVN4a21QUFBRVEYwcnc2NFNIQ3dRMGRVLwpTT0RubnMzY1E2SXBOWFdvV3J3enhRZTVwNHlEZzJp
    OWJoeG1NbmJPUkhoakdPeEx6NXd2WGxjYVh6bkVwdkx3CmZ1ZjcrT251TVltbEVVei8vQU9HYXc5
    Qk45K3hyNWRJLythQjFOc3RrUzY3YVlhN05kcEZjaGlvMlBIY3AvZlIKV0pDUnl5K3RHcEk0UElG
    bXpyZXdIVVZKSmozcXlSZm80ZVRXUmJjRG92dXdoUWVGdzhnTGc5RS9WWFVZdGcraQp2WVBQQkVo
    Y3hTd29sQ3JMTHRaY0QrSlFHQytVMjdVVXJMclk5SVVMVEZ0MnpBc3p5aDlneVVTNU9jR1pjT3pZ
    CmliYTBSQzh0alR4bmoxQWJSR2wzWWVLNCtPUkk5UExaUitSbzZVV2JSZWMvaEN4cUpUVEcyRDZl
    a2o1SkN0V1YKWG9WZ0N0Q016dXRSanB2M1Q5anFuN2p4b05MZWNDVVpRaVhyL2RsdjVHSFFiOGdR
    SUtmNTluUUZDYmtFVldGbwpjeFJZbGlJNDU2bVc1NHFNeGNteWFycTRGUFphaGFqMU9Xc1VteTVC
    c1dNV2FsZ243dkZpOFhHRWVLQTgvZmRMCk5MMjlvcHRLdXpJSG45Y25aamJNWWNlOHNxZjNsQ2U5
    NUxURFNkOXkvbjZURDVna1hHYVNXYUR0cUMydUZ6ckwKVFZhUFNObElOVXJDLytqc2l6WVpBb0lC
    QVFEQ0dvNmFxVE82U2FsMUdkRXVhU2xBa1FtbjE5VzJWQ09TaCtoWApKOWdMZ0tVVUNSSzYxMFNO
    T1ZmL2dTbTcydlZGMGZoTXR3YnpXVThHOVdRKzd0YlB0QnV2cXA4eVJTVW9EVWhlCjYxL0JwRFBk
    cDJIYm5QL3VNZGxiMDZJQjdoSGQ5eWxXYTVYZEpJQjZTUWFTNjlVTm5YZkNYMWJOU09DekVyaVcK
    ak5XNlFRRWRzNGRTdXZDZnk3NjREZzRjLzFWQWU3dzNoMmh4UFZVT2tUWG9hWnBHcExaVHlDczNi
    cXBLdnRMVgpubTZqU1ROM3ptNUZpUjhwQjVFWWwyTmRYUk5aQWtQb253dTdxbWdWbGNvckcyN3Vi
    Z3pCcGZtQ2NmWjU0UjhjCmQrZm16UmNHeUE0Tll1Y1lhOXgrRHdFVjVwSE5sdExHQUErZ0ZCQjh4
    K3l2QUU1MUFvSUJBUUMzWjlPV3VaVm0KS3B0amJNZ3FzVUJwQm5BSy9YdWtOM0tJdzlOUVJjRzZn
    UjdEeGl4RjhXYTRyTTJObW5ZclR5a3dRODIrZ1NNQQpPRjdsSGZsOUg3WkZpSmdZbXd6eGJyaFNZ
    NWY0c01lbm5TMG5tcXdRbkFlRWM2emx6L1dxdzNKWkczckJnbFJMCnR2cCs5b205eVF2aWhsUkcw
    bjhkS1Q3UTBPWndYMlVOVVV2MUFvdEZHa1BJekMxM3pOd2lwbzRSRG0rR2ttVm0KbTVhK2hRaUts
    VWh5SkFDZWNHTnFNaDkyTkJnZXEyVnB5SEZmc1A3MXN4aFVsbksveFd1YnJFdEt0MjRoZFFFTAp0
    ODdlR0ZuSUQ1RE1kaUtvV3ZCcWZzaXNsWkRtWjUwcUxrQ1FRRmg2M2l4MU5HbFp6YnFMN0xKU0JS
    bXBhKzBFCmJ3WEtMVldkb0lsZkFvSUJBQ3JvNUEyY3lpcXNqaUd0QzJsUEppZDM2TUtLSEZ5cVRS
    TGZxS1ZiMFk3NWFZVDgKWEgraGh5NFJOenJzdXVVa2lvUmMzcDlXOXRwbEsrdEY1RnRsUVdlNVVV
    V01XcFVxWkFSdXEwa1FqNktuUWpBRwpDTVFiK1JnWFBRM253ekRhQ0draGNxb0FMcWtzb0pwbitt
    UVFicEVMOXFXcG5lN1Q1Wml3MHMyMVpLcEFKSmNFClVTNGcxWUQ5OGJPT3ArQVJNaStIS3h5N2Vv
    Tk9JN2VNc25ZbW9reHJyVUxvUldXRHVYRzhyYTg3endtWjdSN1gKSzltRGJyZ0xUREE3aDJQa1o1
    cU52YVYzUTRqQkt6RmFZODhUeVhvOEtlWEZZMXRMQmtuN1VuMWdwSXVKVzBYTQpoQTdCaG9VSGt6
    N3E0anFOTmo1VTBWT2tQOUFMbjNsMldRUjI5T0VDZ2dFQWVsOThmb1UxZWdYVHlITTgyNytKCkNv
    cVJGOFFxUzFmencrMWxnWm9KdVRlT0gzS0s5K0FxZWU1UytMaW5RQjZCalFLd3RQdlZMc0J1RU5I
    L05jMkQKQU1Jek9iZTYyeHpWUDZQVU1zdEJiRVVqYTlsNEZWMEdad29Id3c4UEMvRjh5cGZiUUdL
    RmZEK0t4RXdiZTlZNQpaOXZaUDZnVHlKRk1xR2U2V2lCTWZLWlIyQmpxZENFaU9VaUN6ZnlTcFV3
    Y1hxVVRKT2RwWVIxUFo2KzhFenVvCkt3QjZxVHkwR0pkNUJwV2J3bHI2UDZyT2V0ck9RNEpNS2FS
    NHpCd2R3TEVsUzZVNGhucGJTRVpNY1VRdUk1Ni8KTHExa1VwRGErVE8vRWVoNTFrSXNTNGl3NjQ4
    RGVuZmpraEIyZXNVYVEyS2JXTDZ1Y0t6aWFLTHJhZ3IxcFVjSQpZUUtDQVFFQXM2cGx5clIrZVAv
    RS9ZUnlmNnQrODZWRkhVeUd2cXZvSVE2bnJ3NXh5ckhCQUhKeksrTCtDay9mCk5QYnJyUVVCaG40
    WDBGSURFWHVqQ0RsVGM2RFhDWWpZcVd5K3ZRaHZTaEFqWUtrbExCM0tyYXlUc0lKTVhmRHMKcUpz
    VG9EVC9RbnJ0aGlmcktOekRWOEQrOGpVTDZBZ3dYUkJBTXNWalI2YkhCWlZCZEptZ1RNbUpTM1Uv
    SDN5KwpjcXpGS3hJTkJaQ0NDeitTK2c3SXVlTnB6SHBONUlwQUIwM3kwVml1bjZmNERLMkJoeGRQ
    RUNVMXFtaXJ0bVJLCkh2azA1WlJEdEFhV01TSWRXQVlTWHZQSGtCcDQzSDVLTnBaWHZScy9tbUc2
    cWEwSVlGZ1JmSkRuRXA4RmM0RFgKTm0xY0FFeXpsaFBUM1E4Vi9OanJmekMreDViOVNBPT0KLS0t
    LS1FTkQgUFJJVkFURSBLRVktLS0tLQo=
  type: kubernetes.io/tls
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: task2
  namespace: lesson231
spec:
  selector:
    matchLabels:
      app: task2
  template:
    metadata:
      labels:
        app: task2
    spec:
      containers:
      - name: task2-nginx
        image: nginx:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        volumeMounts:
        - name: web-html
          mountPath: /usr/share/nginx/html
      volumes:
        - name: web-html
          configMap:
            name: nginx-html
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: task2-ingress
  namespace: lesson231
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: test-kuber.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: task2-service
            port:
              number: 80
  tls:
    - hosts:
      - test-kuber.com
      secretName: test-kuber-tls
---
apiVersion: v1
kind: Service
metadata:
  name: task2-service
  namespace: lesson231
spec:
  selector:
    app: task2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
